server:
  port: 8088

spring:
  datasource:
    username: root
    password: dhinesh24
    url: jdbc:mysql://localhost:3306/ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create





